language: node_js
node_js:
- "4.4.5"


before_script:
  - "npm run build;npm install -g mocha;npm install express;npm install request;npm install glob;npm install superagent;node app.js & "

script: "mocha"

after_script: "killall -f node"
